Repository binguliki/IntelliLearn, pull requests merged in 2025-07, with the labels that each got.

#10 Added orb functionality
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/ui/orb.jsx
  frontend/src/pages/Dashboard.jsx
  package-lock.json
Labels: enhancement

#12 Update README.md
  README.md
Labels: documentation

#16 Fix/auth using supabase
  frontend/.gitignore
  frontend/package-lock.json
  frontend/package.json
  frontend/public/vite.svg
  frontend/src/App.jsx
  frontend/src/components/Navbar.jsx
  frontend/src/components/ProtectedRoute.jsx
  frontend/src/contexts/UserContext.jsx
  frontend/src/libs/supabase.js
  frontend/src/pages/ChatPage.jsx
  frontend/src/pages/Dashboard.jsx
  frontend/src/pages/LoginPage.jsx
  frontend/src/pages/SignUpPage.jsx
Labels: enhancement

#18 Fix/session storage
  backend/server.py
  frontend/src/components/Navbar.jsx
  frontend/src/contexts/UserContext.jsx
  frontend/src/hooks/use-audio-recording.jsx
  frontend/src/libs/db.js
  frontend/src/pages/ChatPage.jsx
Labels: enhancement, help wanted
